name: TDD Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    # This forces GitHub to look inside your backlogd directory for all commands
    defaults:
      run:
        working-directory: ./backlogd

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, sqlite3

    - name: Copy .env File
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    # Running Unit and Feature tests only for your Green Phase!
    - name: Execute Unit and Feature Test Suites
      run: php artisan test